translation:
    locales: ["en", "de"]
    # edit_in_place:
    #     enabled: false
    #     config_name: app
    #
    auto_add_missing_translations:
        enabled: true
        config_name: "wiki"

    webui:
        enabled:              true
        allow_create:         true
        allow_delete:         true

    # Extend the debug profiler with information about requests.
    symfony_profiler:

        # Turn the symfony profiler integration on or off. Defaults to kernel debug mode.
        enabled:              true
        formatter:            null

    configs:
        app:
            dirs: ["%kernel.project_dir%/templates"]
            output_dir: "%kernel.project_dir%/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            output_format: xlf
        user:
            dirs: ["%kernel.project_dir%/lib/stewie/user-bundle/Resources/translations"]
            output_dir: "%kernel.project_dir%/lib/stewie/user-bundle/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            output_format: xlf
        wiki:
            dirs: ["%kernel.project_dir%/lib/stewie/wiki-bundle/Resources/translations"]
            output_dir: "%kernel.project_dir%/lib/stewie/wiki-bundle/Resources/translations"
            excluded_names: ["*TestCase.php", "*Test.php"]
            excluded_dirs: [cache, data, logs]
            output_format: xlf
