twig:
    default_path: '%kernel.project_dir%/templates'
    # UserBundle
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']

    globals:
        stewie_user_register: true
