vich_uploader:
    db_driver: orm

    mappings:

        user_avatar_user:
            uri_prefix: ''
            upload_destination: '%kernel.project_dir%/uploads/avatar/group'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            # namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        user_avatar_group:
            uri_prefix: ''
            upload_destination: '%kernel.project_dir%/uploads/avatar/group'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        user_avatar_role:
            uri_prefix: ''
            upload_destination: '%kernel.project_dir%/uploads/avatar/role'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
