#index:
#    path: /
#    controller: App\Controller\DefaultController::index
stewie_skeleton:
    resource: "@StewieSkeletonBundle/Controller/"
    type:     annotation

stewie_wiki:
    resource: "@StewieWikiBundle/Controller/"
    type:     annotation
#stewie_wiki_end

stewie_user:
    resource: "@StewieUserBundle/Controller/"
    type:     annotation
    prefix:   "{_locale}/"
    defaults:
      _locale: en
    requirements:
      _locale: en|de
#stewie_user_end
