#index:
#    path: /
#    controller: App\Controller\DefaultController::index
stefanwiegmann_skeleton:
    resource: "@StefanwiegmannSkeletonBundle/Controller/"
    type:     annotation

stefanwiegmann_wiki:
    resource: "@StefanwiegmannWikiBundle/Controller/"
    type:     annotation

stefanwiegmann_user:
    resource: "@StefanwiegmannUserBundle/Controller/"
    type:     annotation
    prefix:   "{_locale}/"
    defaults:
      _locale: en
    requirements:
      _locale: en|de
