#index:
#    path: /
#    controller: App\Controller\DefaultController::index
stefanwiegmann_skeleton:
    resource: "@StefanwiegmannSkeletonBundle/Controller/"
    type:     annotation

stefanwiegmann_wiki:
    resource: "@StefanwiegmannWikiBundle/Controller/"
    type:     annotation
